[package]
name = "capture-dns"
version = "0.3.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
hickory-proto = { version = "*", default-features = false }
clap = { version = "*", features = ["derive"] }
eyre = "*"
pcap = "*"

[profile.release]
lto = true
