[package]
name = "capture-dns"
version = "0.1.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2018"

[dependencies]
trust-dns-proto = "*"
structopt = "*"
structopt-derive = "*"
failure = "*"
pcap = "0.8"

[profile.release]
lto = true
