[package]
name = "capture-dns"
version = "0.2.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
trust-dns-proto = "*"
clap = { version = "*", features = ["derive"] }
eyre = "*"
pcap = "*"

[profile.release]
lto = true
