[package]
name = "capture-dns"
version = "0.1.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
trust-dns-proto = "*"
structopt = "*"
structopt-derive = "*"
failure = "*"
pcap = "*"

[profile.release]
lto = true
